# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

#helm upgrade --cleanup-on-fail \
#  --install test-jupyterhub-helm jupyterhub/jupyterhub \
#  --namespace test-jupyterhub-helm \
#  --version=1.2.0 \
#  --values config.yaml

rbac:
  enabled: true

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

scheduling:
  userPlaceholder:
    enabled: false
  userScheduler:
    enabled: false

proxy:
  chp:
    networkPolicy:
      enabled: false
      interNamespaceAccessLabels: "accept"
  service:
    type: ClusterIP

route:
  enabled: true
  tls:
    enabled: true

hub:
  networkPolicy:
    enabled: false
  image:
    tag: "1.2.0"

singleuser:
  # Set to legacy implementation of jupyter notebook, need to check extensions before upgrading to jupyterhub 2.0.0 and jupyterlab
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html#selecting-a-user-interface
  # This is the default with JupyterHub 1.x
  cmd: /opt/app-root/builder/run
  cloudMetadata:
    blockWithIptables: False
  networkPolicy:
    enabled: false
  uid:
  fsgid:
  extraEnv:
    defaultUrl: /tree/
    JUPYTERHUB_SINGLEUSER_APP: "notebook.notebookapp.NotebookApp"
  profileList:
  # Images available at https://github.com/momoadc/jupyter-notebooks/pkgs/container/jupyter-notebooks%2Fpyspark-notebook
    - display_name: "Spark 3.2.0 - Hadoop 3.2 - Python 3.6"
      description: ""
      kubespawner_override:
        image: ghcr.io/momoadc/jupyter-notebooks/pyspark-notebook:v3.2.0-hadoop3.2-py36
      default: true
