{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  {{- if or (((.Values).hub).serviceAccount).annotations ((.Values).route).enabled }}
  annotations:
    {{- with .Values.hub.serviceAccount.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- if ((.Values).route).enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.first: {{  printf "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"%s\"}}" (include "jupyterhub.route.fullname" .) | quote }}
    serviceaccounts.openshift.io/oauth-redirecturi.first: hub/oauth_callback
    serviceaccounts.openshift.io/oauth-want-challenges: 'false'
    {{- end }}
  {{- end }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "persistentvolumeclaims", "secrets", "services"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jupyterhub.hub.fullname" . }}
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: {{ include "jupyterhub.hub.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
