{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "jupyterhub.route.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  {{- end }}
  to:
    kind: Service
    name: {{ include "jupyterhub.proxy-public.fullname" $ }}
    weight: 100
  wildcardPolicy: None
{{- end }}